---
- name: "Create flavors"
  os_nova_flavor:
    state: "{{ item.state | default('present') }}"
    name: "{{ item.name }}"
    ram: "{{ item.ram }}"
    vcpus: "{{ item.vcpus }}"
    disk: "{{ item.disk }}"
  with_items:
    - "{{ testbed_flavors }}"
